# Generated by Django 5.2.5 on 2025-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_product'),
        ('products', '0004_productrequest_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
