# Generated by Django 5.2.5 on 2025-09-03 18:41

from django.conf import settings
from django.db import migrations, models


def deactivate_existing_requests(apps, schema_editor):
    ProductRequest = apps.get_model('products', 'ProductRequest')
    # Set all existing records to inactive to satisfy the upcoming unique constraint
    ProductRequest.objects.all().update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    migrations.RunPython(deactivate_existing_requests, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_request_per_user'),
        ),
    ]
