# Generated by Django 5.2.5 on 2025-08-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField(default=50000, help_text='Amount in paise (e.g., 50000 = ₹500.00)')),
                ('currency', models.CharField(default='INR', max_length=10)),
            ],
            options={
                'verbose_name': 'Payment configuration',
                'verbose_name_plural': 'Payment configuration',
            },
        ),
    ]
