# Generated by Django 5.2.5 on 2025-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
