# Generated by Django 5.2.5 on 2025-09-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentConfig',
        ),
    ]
